#!/bin/sh
#PBS -N wp80_test0
# for upf & mcf, use ppn=3; for wp, xi, & x2, use ppn=1
#PBS -l nodes=1:ppn=1

# 7 cosmologies x 5 boxes each x 100 hod
##PBS -t 0-3499%24
#PBS -t 0-0%1

#PBS -o output/$PBS_JOBNAME.out
#PBS -j oe
  
cd $PBS_O_WORKDIR

echo "Hello from $PBS_ARRAYID..."
# Reading config.$PBS_VNODENUM" >> myoutput.$PBS_NODENUM
# Actual command, with data file based on $PBS_VNODENUM:
declare -i cosmo #need to declare variables to do arithmetic
declare -i box
declare -i hod
declare -i cb
declare -i ncb
declare -i ncosmos
declare -i nboxes

# hod10
# 35 = 7 cosmos x 5 boxes
ncosmos=7
nboxes=5
ncb=ncosmos*nboxes
# if run -t 0-349, running 10 hod
# if run -t 0-3499, running 100 hod
hod=${PBS_ARRAYID}/ncb
cb=${PBS_ARRAYID}%ncb
cosmo=cb/nboxes
box=cb%nboxes

#factor_star=8.0
#p=1.0
#savetag="_fstar${factor_star}_p${p}"
savetag=""
#statistics=("marks" "mcf")
#statistics=("xi" "xi2")
statistics=("wp80")
overwrite=true

test=0

workdir=$PBS_O_WORKDIR
cosmofn=/mount/sirocco1/zz681/emulator/CMASS/Gaussian_Process/hod_file/cosmology_camb_test_box_full.dat
for statistic in ${statistics[@]}; do

  result_dir=$workdir/results_$statistic/testing_${statistic}${savetag}
  mkdir -p "${result_dir}"
  savefn="${result_dir}/${statistic}_cosmo_${cosmo}_Box_${box}_HOD_${hod}_test_${test}.dat"

  if [ ! -f $savefn ] || [ $overwrite = true ]; then
    echo "Computing $statistic of cosmo $cosmo hod $hod box $box savetag $savetag"
    mockdir=/mount/sirocco2/zz681/emulator/CMASSLOWZ/test_galaxy_mocks_wp_RSD/test_galaxy_mocks_new_f_env/mocks
    mockname=mock_cosmo_${cosmo}_Box_${box}_HOD_${hod}_test_${test}.mock
    
    if [ $statistic = "upf" ]; then
      meanngalsfn=$workdir/numgals/mean_numgals_testing_hod100_test0.dat
      $workdir/upf_zspace $mockdir/$mockname 5 45 9 $savefn $meanngalsfn $cosmofn $cosmo
    fi
    if [ $statistic = "vpf" ]; then
      meanngalsfn=$workdir/numgals/zero.dat
      $workdir/upf_zspace $mockdir/$mockname 5 45 9 $savefn $meanngalsfn $cosmofn $cosmo
    fi
    if [ $statistic = "wp" ]; then
      echo "python wprp.py $mockdir/$mockname 0.1 50 9 $savefn $cosmofn $cosmo"
      python wprp.py $mockdir/$mockname 0.1 50 9 $savefn $cosmofn $cosmo
    fi
    if [ $statistic = "marks" ]; then
      meanngalsfn=$workdir/numgals/mean_numgals_testing_hod100_test0.dat
      $workdir/marks_zspace $mockdir/$mockname $savefn $meanngalsfn $cosmofn $cosmo $factor_star $p
    fi
    if [ $statistic = "mcf" ] || [ $statistic = "wxi" ]; then
      echo "python markedcf.py $mockdir/$mockname 0.1 50 9 $savefn $markfn $cosmofn $cosmo $statistic"
      marktag=$savetag
      markdir=$workdir/results_marks/testing_marks${marktag}
      markfn=${markdir}/marks_cosmo_${cosmo}_Box_${box}_HOD_${hod}_test_${test}.dat
      python markedcf.py $mockdir/$mockname 0.1 50 9 $savefn $markfn $cosmofn $cosmo $statistic
    fi
    if [ $statistic = "xi" ] || [ $statistic = "xi2" ]; then
      echo "python xi.py $mockdir/$mockname 0.1 50 9 $savefn $cosmofn $cosmo $statistic"
      python xi.py $mockdir/$mockname 0.1 50 9 $savefn $cosmofn $cosmo $statistic
    fi
  fi
done
